version: 2
updates:
  # Enable version updates for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/" # Location of GitHub Actions workflows
    schedule:
      interval: "weekly"

  # Enable version updates for Node.js dependencies
  - package-ecosystem: "npm"
    directory: "/" # Root directory where package.json is located
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5

  # Enable version updates for Python dependencies (if applicable)
  - package-ecosystem: "pip"
    directory: "/" # Root directory where requirements.txt is located
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
